apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions
  namespace: default
rules:
- apiGroups: [""]
  resources: ["configmaps", "serviceaccounts", "services", "pods", "pods/log"]
  verbs: ["create", "delete", "update", "get", "watch", "patch", "list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["create", "delete", "update", "get", "watch", "patch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "update", "get", "watch", "patch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: github-actions
  namespace: default
subjects:
- kind: User
  name: github-actions@substratus-dev.iam.gserviceaccount.com
roleRef:
  kind: Role
  name: github-actions
  apiGroup: rbac.authorization.k8s.io
