apiVersion: v1
kind: Service
metadata:
  name: {{ include "openwebui.fullname" . }}
  labels:
    {{- include "openwebui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{ if or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer") }}
      {{ if .Values.service.httpNodePort }}
      nodePort: {{ .Values.service.httpNodePort }}
      {{ end }}
      {{ end }}
  selector:
    {{- include "openwebui.selectorLabels" . | nindent 4 }}
