apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: kubeai-project
build:
  artifacts:
    - image: substratusai/kubeai
  local:
    push: false
deploy:
  helm:
    releases:
      - name: kubeai
        chartPath: ./charts/kubeai
        setValueTemplates:
          open-webui.enabled: "false"
        skipBuildDependencies: true
portForward:
  - resourceType: service
    resourceName: kubeai
    namespace: default
    port: 80
    localPort: 8000
profiles:
  - name: kubeai-only
    deploy:
      helm:
        releases:
          - name: kubeai
            chartPath: ./charts/kubeai
            setValueTemplates:
              open-webui.enabled: "false"
            skipBuildDependencies: true
  - name: kubeai-only-gke
    build:
      local:
        push: true
    deploy:
      helm:
        releases:
          - name: kubeai
            chartPath: ./charts/kubeai
            valuesFiles:
              - ./charts/kubeai/values-gke.yaml
            setValueTemplates:
              open-webui.enabled: "false"
            skipBuildDependencies: true