apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: kubeai-project
build:
  artifacts:
  - image: substratusai/kubeai
    # NOTE: If you run into this error:
    #
    # Checking cache...
    #  - substratusai/kubeai: Error checking cache.
    # getting hash for artifact "substratusai/kubeai": getting dependencies for "substratusai/kubeai": parsing ONBUILD instructions: retrieving image "gcr.io/distroless/static:nonroot": GET https://gcr.io/v2/token?scope=repository%3Adistroless%2Fstatic%3Apull&service=gcr.io: UNAUTHORIZED: authentication failed
    #
    # Then run "docker pull gcr.io/distroless/static:nonroot" and retry.
    # Disabling cache for the image that uses distroless/static:nonroot does not appear to work:
    #
    # docker:
    #   noCache: true
    #
  - image: substratusai/kubeai-model-loader
    context: ./components/model-loader
  local:
    push: false
deploy:
  helm:
    releases:
    - name: kubeai
      chartPath: ./charts/kubeai
      setValueTemplates:
        open-webui.enabled: false
      skipBuildDependencies: true
portForward:
- resourceType: service
  resourceName: kubeai
  namespace: default
  port: 80
  localPort: 8000

profiles:
- name: kubeai-only
  deploy:
    helm:
      releases:
      - name: kubeai
        chartPath: ./charts/kubeai
        setValueTemplates:
          open-webui.enabled: false
        skipBuildDependencies: true

- name: kubeai-only-gke
  build:
    local:
      push: true
  deploy:
    helm:
      releases:
      - name: kubeai
        chartPath: ./charts/kubeai
        setValueTemplates:
          open-webui.enabled: false
        valuesFiles:
        - ./charts/kubeai/values-gke.yaml
        skipBuildDependencies: true

- name: e2e-test-default
  deploy:
    helm:
      releases:
      - name: kubeai
        chartPath: ./charts/kubeai
        valuesFiles:
        - ./test/e2e/common-values.yaml
        setValueTemplates:
          open-webui.enabled: false
          modelLoading.image: "{{.IMAGE_FULLY_QUALIFIED_substratusai_kubeai_model_loader}}"
        skipBuildDependencies: true
- name: e2e-test-autoscaler-restart
  deploy:
    helm:
      releases:
      - name: kubeai
        chartPath: ./charts/kubeai
        valuesFiles:
        - ./test/e2e/common-values.yaml
        setValueTemplates:
          open-webui.enabled: false
          modelAutoscaling.interval: 1s
          modelAutoscaling.timeWindow: 30s
          modelLoading.image: "{{.IMAGE_FULLY_QUALIFIED_substratusai_kubeai_model_loader}}"
        skipBuildDependencies: true
- name: e2e-test-engine
  deploy:
    helm:
      releases:
      - name: kubeai
        chartPath: ./charts/kubeai
        valuesFiles:
        - ./test/e2e/common-values.yaml
        setValueTemplates:
          open-webui.enabled: false
          modelLoading.image: "{{.IMAGE_FULLY_QUALIFIED_substratusai_kubeai_model_loader}}"
        skipBuildDependencies: true
