# Source: models/templates/models.yaml
apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: deepseek-r1-distill-llama-8b-l4
spec:
  features: [TextGeneration]
  url: hf://deepseek-ai/DeepSeek-R1-Distill-Llama-8B
  engine: VLLM
  args:
    - --max-model-len=8192
    - --max-num-batched-token=8192
    - --max-num-seqs=256
    - --gpu-memory-utilization=0.95
    - --kv-cache-dtype=fp8
    - --disable-log-requests
    - --quantization=fp8
    - --enforce-eager
  env:
    VLLM_ATTENTION_BACKEND: FLASHINFER
  resourceProfile: nvidia-gpu-l4:1
