# Source: models/templates/models.yaml
apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: e5-mistral-7b-instruct-cpu
spec:
  features: [TextEmbedding]
  url: hf://intfloat/e5-mistral-7b-instruct
  engine: VLLM
  resourceProfile: cpu:5
