# Source: models/templates/models.yaml
apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: llama-3.1-supernova-lite-l4
spec:
  features: [TextGeneration]
  url: hf://arcee-ai/Llama-3.1-SuperNova-Lite
  engine: VLLM
  args:
    - --max-model-len=2048
    - --max-num-batched-token=2048
    - --max-num-seqs=1
    - --gpu-memory-utilization=0.95
    - --kv-cache-dtype=fp8
    - --disable-log-requests
    - --quantization=fp8
    - --enforce-eager
  env:
    VLLM_ATTENTION_BACKEND: FLASHINFER
  resourceProfile: nvidia-gpu-l4:1
