# Source: models/templates/models.yaml
apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: opt-125m-cpu
spec:
  features: [TextGeneration]
  # env:
  #   VLLM_RPC_TIMEOUT: "10000"
  #   VLLM_CPU_KVCACHE_SPACE: "1"
  args:
  - --disable-frontend-multiprocessing
  - --max-num-seqs=1
  owner: facebook
  url: hf://facebook/opt-125m
  engine: VLLM
  resourceProfile: cpu:1
