# Source: models/templates/models.yaml
apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: qwen2-500m-instruct-sglang-gpu
spec:
  features:
    - TextGeneration
  url: hf://Qwen/Qwen2.5-0.5B-Instruct
  engine: SGLang
  args:
    - --dtype=half
    - --context-length=2048
    - --mem-fraction-static=0.3
  minReplicas: 0
  resourceProfile: nvidia-gpu-t4:1
