# Source: models/templates/models.yaml
apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: spark-x2.5-4b-sglang-gpu
spec:
  features:
    - TextGeneration
  url: hf://XHToken/Spark-X2.5-4B
  engine: SGLang
  args:
    - --dtype=half
    - --tool-call-parser=spark25
    - --reasoning-parser=qwen3
    - --mem-fraction-static=0.7
    - --context-length=8192
  minReplicas: 0
  resourceProfile: nvidia-gpu-t4:1
