defaults:
  minReplicas: 0
  maxReplicas: 3

catalog:
  # Mistral #
  e5-mistral-7b-instruct-cpu:
    enabled: false
    features: ["TextEmbedding"]
    owner: intfloat
    url: "hf://intfloat/e5-mistral-7b-instruct"
    resourceProfile: CPU:1
    args:
    - --gpu-memory-utilization=0.9
  # Gemma #
  gemma2-2b-cpu:
    enabled: false
    features: ["TextGeneration"]
    owner: google
    url: "ollama://gemma2:2b"
    engine: OLlama
    resourceProfile: CPU:2
  # Llama #
  llama-3.1-8b-instruct-cpu:
    enabled: false
    features: ["TextGeneration"]
    owner: "meta-llama"
    url: "hf://meta-llama/Meta-Llama-3.1-8B-Instruct"
    engine: VLLM
    resourceProfile: CPU:6
    env:
      VLLM_CPU_KVCACHE_SPACE: "4"
    args:
    - --max-model-len=32768
    - --max-num-batched-token=32768
  llama-3.1-8b-instruct-fp8-l4:
    enabled: false
    features: ["TextGeneration"]
    owner: "neuralmagic"
    url: "hf://neuralmagic/Meta-Llama-3.1-8B-Instruct-FP8"
    engine: VLLM
    resourceProfile: L4:1
    args:
    - --max-model-len=16384
    - --max-num-batched-token=16384
    - --gpu-memory-utilization=0.9
  # Nomic #
  nomic-embed-text-cpu:
    enabled: false
    features: ["TextEmbedding"]
    owner: nomic
    url: "ollama://nomic-embed-text"
    engine: OLlama
    resourceProfile: CPU:1
  # Opt #
  opt-125m-cpu:
    enabled: false
    features: ["TextGeneration"]
    owner: facebook
    url: "hf://facebook/opt-125m"
    engine: VLLM
    resourceProfile: CPU:1
  opt-125m-l4:
    enabled: false
    features: ["TextGeneration"]
    owner: facebook
    url: "hf://facebook/opt-125m"
    engine: VLLM
    resourceProfile: L4:1
  # Qwen #
  qwen2-500m-cpu:
    enabled: false
    features: ["TextGeneration"]
    owner: alibaba
    url: "ollama://qwen2:0.5b"
    engine: OLlama
    resourceProfile: CPU:1

