resourceProfiles:
  nvidia-gpu-l4:
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-l4"
      cloud.google.com/gke-spot: "true"
  nvidia-gpu-h100:
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-h100-80gb"
      cloud.google.com/gke-spot: "true"
  nvidia-gpu-a100-80gb:
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-a100-80gb"
      cloud.google.com/gke-spot: "true"
  nvidia-gpu-a100-40gb:
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
      cloud.google.com/gke-spot: "true"
  google-tpu-v5e-1x1:
    imageName: google-tpu
    limits:
      google.com/tpu: 1
    nodeSelector:
      cloud.google.com/gke-tpu-accelerator: tpu-v5-lite-podslice
      cloud.google.com/gke-tpu-topology: "1x1"
      cloud.google.com/gke-spot: "true"
  google-tpu-v5e-2x2:
    imageName: google-tpu
    limits:
      google.com/tpu: 1
    nodeSelector:
      cloud.google.com/gke-tpu-accelerator: tpu-v5-lite-podslice
      cloud.google.com/gke-tpu-topology: "2x2"
      cloud.google.com/gke-spot: "true"
  google-tpu-v5e-2x4:
    imageName: google-tpu
    limits:
      google.com/tpu: 1
    nodeSelector:
      cloud.google.com/gke-tpu-accelerator: tpu-v5-lite-podslice
      cloud.google.com/gke-tpu-topology: "2x4"
      cloud.google.com/gke-spot: "true"

cacheProfiles:
  standard-filestore:
    sharedFilesystem:
      storageClassName: "standard-rwx"
  premium-filestore:
    sharedFilesystem:
      storageClassName: "premium-rwx"