{{- range $name, $model := .Values.catalog}}
{{- if or $model.enabled $.Values.all.enabled }}
---
apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: {{ $name }}
spec:
  features: {{ $model.features }}
  {{- with $model.owner }}
  owner: {{ . }}
  {{- end }}
  url: {{ $model.url }}
  {{- with $model.adapters }}
  adapters:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $model.engine }}
  engine: {{ . }}
  {{- end }}
  {{- with $model.args }}
  args:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $model.env }}
  env:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $model.minReplicas }}
  minReplicas: {{ . }}
  {{- end }}
  {{- with $model.maxReplicas }}
  maxReplicas: {{ . }}
  {{- end}}
  {{- with $model.targetRequests }}
  targetRequests: {{ . }}
  {{- end}}
  {{- with $model.scaleDownDelaySeconds }}
  scaleDownDelaySeconds: {{ . }}
  {{- end}}
  {{- with $model.resourceProfile }}
  resourceProfile: {{ . }}
  {{- end}}
  {{- with $model.cacheProfile }}
  cacheProfile: {{ . }}
  {{- end}}
{{- end}}
{{- end}}