apiVersion: v1
kind: Pod
metadata:
  name: bench
spec:
  restartPolicy: Never
  containers:
    - name: bench
      image: us-central1-docker.pkg.dev/substratus-dev/default/benchmark-multi-turn-chat-go:v0.1.1
      imagePullPolicy: Always
      command: ["sleep", "infinity"]
      env:
      - name: OPENAI_BASE_URL
        value: http://kubeai/openai/v1
      resources:
        requests:
          cpu: 2
          memory: 2G
        limits:
          cpu: 2
          memory: 2G