apiVersion: v1
kind: Pod
metadata:
  name: bench
spec:
  restartPolicy: Never
  containers:
    - name: bench
      image: substratusai/multi-turn-chat-go:v0.0.2
      imagePullPolicy: Always
      args: 
        - --threads=./data/small.json
        - --thread-count=40
        - --max-concurrent-threads=10
        - --request-model=opt-125m-cpu
        - --max-completion-tokens=10
        - --request-timeout=6m
        - --no-shuffle
      env:
      - name: OPENAI_BASE_URL
        value: http://kubeai/openai/v1
      resources:
        requests:
          cpu: 4
          memory: 4G
        limits:
          cpu: 4
          memory: 4G