apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  annotations:
    lingo.substratus.ai/models: backend
  labels:
    app: backend
spec:
  replicas: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kennethreitz/httpbin
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /get
              port: 80
