apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lingo
subjects:
  - kind: ServiceAccount
    name: lingo
    namespace: default
roleRef:
  kind: Role
  name: lingo
  apiGroup: rbac.authorization.k8s.io
