apiVersion: apps/v1
kind: Deployment
metadata:
  name: lingo
  labels:
    app: lingo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lingo
  template:
    metadata:
      labels:
        app: lingo
    spec:
      serviceAccountName: lingo
      containers:
        - name: main
          image: us-central1-docker.pkg.dev/substratus-dev/substratus/lingo
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: lingo-env
          volumeMounts:
            - name: secrets
              mountPath: /secrets
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 1
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
      - name: secrets
        secret:
          secretName: lingo-secrets
          optional: true