apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: llama-3.1-70b-instruct-fp8-h100
spec:
  features: [TextGeneration]
  url: hf://neuralmagic/Meta-Llama-3.1-70B-Instruct-FP8
  engine: VLLM
  args:
    - --enable-prefix-caching
    - --max-model-len=16384
    - --max-num-batched-token=16384
    - --gpu-memory-utilization=0.95
    - --disable-log-requests
    - --kv-cache-dtype=fp8
  resourceProfile: nvidia-gpu-h100:1
  minReplicas: 8
  maxReplicas: 8
