apiVersion: v1
kind: Pod
metadata:
  name: chat-benchmark
spec:
  restartPolicy: Never
  containers:
    - name: bench
      image: $IMG
      command: ["sleep", "infinity"]
      resources:
        requests:
          cpu: 6
          ephemeral-storage: 10Gi
          memory: 24Gi
        limits:
          cpu: 6
          ephemeral-storage: 10Gi
          memory: 24Gi