authors:
  nstogner:
    name: Nick Stogner
    description: Creator
    url: https://www.linkedin.com/in/nstogner/
    avatar: https://avatars.githubusercontent.com/u/10274189
  samstoelinga:
    name: Sam Stoelinga
    description: Creator
    url: https://www.linkedin.com/in/samstoelinga/
    avatar: https://avatars.githubusercontent.com/u/388784