apiVersion: v1
kind: Pod
metadata:
  name: chat-benchmark
spec:
  restartPolicy: Never
  containers:
    - name: bench
      image: us-central1-docker.pkg.dev/substratus-dev/default/kubeai-benchmark-chat:v0.0.2
      command: ["sleep", "infinity"]
      resources:
        requests:
          cpu: 6
          ephemeral-storage: 10Gi
          memory: 24Gi
        limits:
          cpu: 6
          ephemeral-storage: 10Gi
          memory: 24Gi