apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: dev
  annotations:
    # Have the controller send requests to localhost to allow for
    # running the controller locally (assuming a port-forward is in place).
    model-pod-ip: "127.0.0.1"
    model-pod-port: "7000" 
spec:
  features: ["TextGeneration"]
  owner: facebook
  url: hf://facebook/opt-125m
  engine: VLLM
  resourceProfile: cpu:1
  minReplicas: 1
  maxReplicas: 3
  args:
    # This revision does not contain its own chat template.
    - --revision=27dcfa74d334bc871f3234de431e71c6eeba5dd6
    - --chat-template=/config/chat-template.jinja
    - --swap-space=1
  env:
    VLLM_CPU_KVCACHE_SPACE: "2"
  files:
    - path: "/config/chat-template.jinja"
      content: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ 'Question:\n' + message['content'] + '\n\n' }}{% elif message['role'] == 'system' %}\n{{ 'System:\n' + message['content'] + '\n\n' }}{% elif message['role'] == 'assistant' %}{{ 'Answer:\n'  + message['content'] + '\n\n' }}{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ 'Answer:\n' }}{% endif %}{% endfor %}"
    - path: "/config/prompt.txt"
      content: "prompt content"
---
# Service for port-fowarding to the model:
#
# while true; do kubectl port-forward service/dev-model 7000:7000; done
#
apiVersion: v1
kind: Service
metadata:
  name: dev-model
spec:
  selector:
    model: dev
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 8000