apiVersion: v1
kind: Service
metadata:
  name: vllm-direct
  labels:
    app: vllm-direct
spec:
  selector:
    app.kubernetes.io/name: vllm
  ports:
    - name: http
      protocol: TCP
      port: 80       # The port exposed by the Service.
      targetPort: 8000 # The container port that your pods are listening on.
  type: ClusterIP

