apiVersion: v1
kind: Pod
metadata:
  name: dev-load
spec:
  restartPolicy: Never
  containers:
    - name: k6
      image: grafana/k6
      args: ["run", "/config/k6.js"] #, "--http-debug"]
      volumeMounts:
        - name: config
          mountPath: /config
  volumes:
    - name: config
      configMap:
        name: dev-load