apiVersion: v1
kind: Pod
metadata:
  name: bench
spec:
  restartPolicy: Never
  containers:
    - name: bench
      image: us-central1-docker.pkg.dev/substratus-dev/default/benchmark-multi-turn-chat-go
      imagePullPolicy: Always
      args: 
        - --threads=./data/small.json
        - --thread-count=45
        - --max-concurrent-threads=15
        - --request-model=qwen2.5-coder-1.5b-cpu
        - --max-completion-tokens=4
        - --request-timeout=6m
        - --no-shuffle
      env:
      - name: OPENAI_BASE_URL
        value: http://kubeai/openai/v1
      - name: HUGGING_FACE_HUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: kubeai-huggingface
            key: token
      resources:
        requests:
          cpu: 4
          memory: 4G
        limits:
          cpu: 4
          memory: 4G