apiVersion: v1
kind: Pod
metadata:
  name: bench
spec:
  restartPolicy: Never
  containers:
    - name: bench
      image: us-central1-docker.pkg.dev/substratus-dev/default/benchmark-multi-turn-chat-go
      args: 
        - --threads=./data/large.json
        - --thread-count=3
        - --max-concurrent-threads=3
        - --request-model=llama-3.1-8b-instruct-cpu
        - --max-completion-tokens=10
        - --tokenizer-model=meta-llama/Meta-Llama-3.1-8B-Instruct
        - --request-timeout=1m
      env:
      - name: OPENAI_BASE_URL
        value: http://kubeai/openai/v1
      - name: HUGGING_FACE_HUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: kubeai-huggingface
            key: token
      resources:
        requests:
          cpu: 4
          memory: 4G
        limits:
          cpu: 4
          memory: 4G