{{- if and .Values.secrets.aws.create (and (not (empty .Values.secrets.aws.accessKeyId)) (not (empty .Values.secrets.aws.secretAccessKey))) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeai.awsSecretName" . }}
  labels:
    {{- include "kubeai.labels" . | nindent 4 }}
data:
  accessKeyId: {{ .Values.secrets.aws.accessKeyId | b64enc }}
  secretAccessKey: {{ .Values.secrets.aws.secretAccessKey | b64enc }}
{{- end }}