apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeai.fullname" . }}-config
  labels:
    {{- include "kubeai.labels" . | nindent 4 }}
data:
  system.yaml: |
    secretNames:
      huggingface: {{ include "kubeai.huggingfaceSecretName" . }}
    resourceProfiles:
      {{- .Values.resourceProfiles | toYaml | nindent 6 }}
    modelServers:
      {{- .Values.modelServers | toYaml | nindent 6 }}
    autoscaling:
      {{- .Values.autoscaling | toYaml | nindent 6 }}