# Only create the secret if the token is not empty.
# See: https://github.com/substratusai/kubeai/issues/232
{{- if and .Values.secrets.huggingface.create (not (empty .Values.secrets.huggingface.token)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeai.huggingfaceSecretName" . }}
  labels:
    {{- include "kubeai.labels" . | nindent 4 }}
data:
  token: {{ .Values.secrets.huggingface.token | b64enc }}
{{- end }}