# Create securityContextConstraints for the model pods if running on OpenShift.
# This is needed because pods in OpenShift run with the restricted-v2 SCC by
# default which do not allow a container to start with uid=0
# (The model pod images run as the root user)
{{- if .Capabilities.APIVersions.Has "security.openshift.io/v1" }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ include "kubeai.fullname" . }}-models
allowPrivilegeEscalation: false
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
seccompProfiles:
  - runtime/default
requiredDropCapabilities:
  - ALL
users:
  - system:serviceaccount:{{ .Release.Namespace }}:{{ include "models.serviceAccountName" . }}
{{- end }}
