apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeai.fullname" . }}
  labels:
    {{- include "kubeai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
    - name: http-metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
      {{- with .Values.service.metricsNodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "kubeai.selectorLabels" . | nindent 4 }}
