{{- if .Values.metrics.prometheusOperator.vLLMPodMonitor.enabled }}
apiVersion: {{ .Values.metrics.prometheusOperator.vLLMPodMonitor.apiVersion }}
kind: PodMonitor
metadata:
  name: {{ include "kubeai.fullname" . }}-vllm
  labels:
    {{- include "kubeai.labels" . | nindent 4 }}
    {{- with .Values.metrics.prometheusOperator.vLLMPodMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vllm
  podMetricsEndpoints:
  - port: http
{{- end }}
