name: Build and Push kubeai-model-loader Docker image

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read # to fetch the repository content
      id-token: write # for signing attestation(s) with GitHub OIDC Token
      packages: write
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      context: ./components/model-loader
      file: Dockerfile
      cache: true
      cache-scope: kubeai-model-loader
      cache-mode: max
      meta-images: ghcr.io/${{ github.repository_owner }}/kubeai-model-loader
      set-meta-labels: true
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
