name: Publish docs

on:
  push:
    branches:
      - main

jobs:
  publish-docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: |
         git fetch origin
         # This is needed because otherwise mkdocs removes the index.yaml file.
         # Get the latest index.yaml from gh-pages branch.
         git checkout gh-pages
         git pull origin gh-pages
         cp index.yaml /tmp/index.yaml
         git checkout main
         git pull origin main
         cp /tmp/index.yaml docs/index.yaml
         pip install -r docs/requirements.txt
      - run: make generate-kubernetes-api-reference
      - run: mkdocs gh-deploy