name: Tests
run-name: Run tests by @${{ github.actor }}

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.21.0"

      - name: Run unit tests
        run: make test
