name: Tests
run-name: Run tests by @${{ github.actor }}

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run unit tests
        run: make test-unit

  integration:
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run integration tests
        run: make test-integration

  e2e-quickstart:
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.24.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Install helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Start kind cluster
        run: kind create cluster

      - name: Run the quickstart tests
        run: make test-e2e-quickstart